# Generated by Django 5.2.8 on 2025-11-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=10, unique=True)),
                ('title_type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(blank=True, max_length=300, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('genres', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-release_year'],
            },
        ),
    ]
